package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_DATE extends StructObject {
	public CK_DATE() {
		super();
	}
	public CK_DATE(Pointer pointer) {
		super(pointer);
	}
	/**
	 * the year ("1900" - "9999")<br>
	 * C type : CK_CHAR[4]
	 */
	@Array({4}) 
	@Field(0) 
	public Pointer<Byte > year() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * the month ("01" - "12")<br>
	 * C type : CK_CHAR[2]
	 */
	@Array({2}) 
	@Field(1) 
	public Pointer<Byte > month() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * the day   ("01" - "31")<br>
	 * C type : CK_CHAR[2]
	 */
	@Array({2}) 
	@Field(2) 
	public Pointer<Byte > day() {
		return this.io.getPointerField(this, 2);
	}
}
