package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.rejna.pkcs11.Version;

import xltck.XltCkLibrary.CK_C_CancelFunction;
import xltck.XltCkLibrary.CK_C_CloseAllSessions;
import xltck.XltCkLibrary.CK_C_CloseSession;
import xltck.XltCkLibrary.CK_C_CopyObject;
import xltck.XltCkLibrary.CK_C_CreateObject;
import xltck.XltCkLibrary.CK_C_Decrypt;
import xltck.XltCkLibrary.CK_C_DecryptDigestUpdate;
import xltck.XltCkLibrary.CK_C_DecryptFinal;
import xltck.XltCkLibrary.CK_C_DecryptInit;
import xltck.XltCkLibrary.CK_C_DecryptUpdate;
import xltck.XltCkLibrary.CK_C_DecryptVerifyUpdate;
import xltck.XltCkLibrary.CK_C_DeriveKey;
import xltck.XltCkLibrary.CK_C_DestroyObject;
import xltck.XltCkLibrary.CK_C_Digest;
import xltck.XltCkLibrary.CK_C_DigestEncryptUpdate;
import xltck.XltCkLibrary.CK_C_DigestFinal;
import xltck.XltCkLibrary.CK_C_DigestInit;
import xltck.XltCkLibrary.CK_C_DigestKey;
import xltck.XltCkLibrary.CK_C_DigestUpdate;
import xltck.XltCkLibrary.CK_C_Encrypt;
import xltck.XltCkLibrary.CK_C_EncryptFinal;
import xltck.XltCkLibrary.CK_C_EncryptInit;
import xltck.XltCkLibrary.CK_C_EncryptUpdate;
import xltck.XltCkLibrary.CK_C_Finalize;
import xltck.XltCkLibrary.CK_C_FindObjects;
import xltck.XltCkLibrary.CK_C_FindObjectsFinal;
import xltck.XltCkLibrary.CK_C_FindObjectsInit;
import xltck.XltCkLibrary.CK_C_GenerateKey;
import xltck.XltCkLibrary.CK_C_GenerateKeyPair;
import xltck.XltCkLibrary.CK_C_GenerateRandom;
import xltck.XltCkLibrary.CK_C_GetAttributeValue;
import xltck.XltCkLibrary.CK_C_GetFunctionList;
import xltck.XltCkLibrary.CK_C_GetFunctionStatus;
import xltck.XltCkLibrary.CK_C_GetInfo;
import xltck.XltCkLibrary.CK_C_GetMechanismInfo;
import xltck.XltCkLibrary.CK_C_GetMechanismList;
import xltck.XltCkLibrary.CK_C_GetObjectSize;
import xltck.XltCkLibrary.CK_C_GetOperationState;
import xltck.XltCkLibrary.CK_C_GetSessionInfo;
import xltck.XltCkLibrary.CK_C_GetSlotInfo;
import xltck.XltCkLibrary.CK_C_GetSlotList;
import xltck.XltCkLibrary.CK_C_GetTokenInfo;
import xltck.XltCkLibrary.CK_C_InitPIN;
import xltck.XltCkLibrary.CK_C_InitToken;
import xltck.XltCkLibrary.CK_C_Initialize;
import xltck.XltCkLibrary.CK_C_Login;
import xltck.XltCkLibrary.CK_C_Logout;
import xltck.XltCkLibrary.CK_C_OpenSession;
import xltck.XltCkLibrary.CK_C_SeedRandom;
import xltck.XltCkLibrary.CK_C_SetAttributeValue;
import xltck.XltCkLibrary.CK_C_SetOperationState;
import xltck.XltCkLibrary.CK_C_SetPIN;
import xltck.XltCkLibrary.CK_C_Sign;
import xltck.XltCkLibrary.CK_C_SignEncryptUpdate;
import xltck.XltCkLibrary.CK_C_SignFinal;
import xltck.XltCkLibrary.CK_C_SignInit;
import xltck.XltCkLibrary.CK_C_SignRecover;
import xltck.XltCkLibrary.CK_C_SignRecoverInit;
import xltck.XltCkLibrary.CK_C_SignUpdate;
import xltck.XltCkLibrary.CK_C_UnwrapKey;
import xltck.XltCkLibrary.CK_C_Verify;
import xltck.XltCkLibrary.CK_C_VerifyFinal;
import xltck.XltCkLibrary.CK_C_VerifyInit;
import xltck.XltCkLibrary.CK_C_VerifyRecover;
import xltck.XltCkLibrary.CK_C_VerifyRecoverInit;
import xltck.XltCkLibrary.CK_C_VerifyUpdate;
import xltck.XltCkLibrary.CK_C_WaitForSlotEvent;
import xltck.XltCkLibrary.CK_C_WrapKey;
/**
 * <i>native declaration : xltCk.h:1476</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_FUNCTION_LIST extends StructObject {
	public CK_FUNCTION_LIST() {
		super();
	}
	public CK_FUNCTION_LIST(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_VERSION
	@Field(0) 
	public Version version() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : CK_C_Initialize
	@Field(1) 
	public Pointer<CK_C_Initialize > C_Initialize() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : CK_C_Initialize
	@Field(1) 
	public CK_FUNCTION_LIST C_Initialize(Pointer<CK_C_Initialize > C_Initialize) {
		this.io.setPointerField(this, 1, C_Initialize);
		return this;
	}
	/// C type : CK_C_Finalize
	@Field(2) 
	public Pointer<CK_C_Finalize > C_Finalize() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : CK_C_Finalize
	@Field(2) 
	public CK_FUNCTION_LIST C_Finalize(Pointer<CK_C_Finalize > C_Finalize) {
		this.io.setPointerField(this, 2, C_Finalize);
		return this;
	}
	/// C type : CK_C_GetInfo
	@Field(3) 
	public Pointer<CK_C_GetInfo > C_GetInfo() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : CK_C_GetInfo
	@Field(3) 
	public CK_FUNCTION_LIST C_GetInfo(Pointer<CK_C_GetInfo > C_GetInfo) {
		this.io.setPointerField(this, 3, C_GetInfo);
		return this;
	}
	/// C type : CK_C_GetFunctionList
	@Field(4) 
	public Pointer<CK_C_GetFunctionList > C_GetFunctionList() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : CK_C_GetFunctionList
	@Field(4) 
	public CK_FUNCTION_LIST C_GetFunctionList(Pointer<CK_C_GetFunctionList > C_GetFunctionList) {
		this.io.setPointerField(this, 4, C_GetFunctionList);
		return this;
	}
	/// C type : CK_C_GetSlotList
	@Field(5) 
	public Pointer<CK_C_GetSlotList > C_GetSlotList() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : CK_C_GetSlotList
	@Field(5) 
	public CK_FUNCTION_LIST C_GetSlotList(Pointer<CK_C_GetSlotList > C_GetSlotList) {
		this.io.setPointerField(this, 5, C_GetSlotList);
		return this;
	}
	/// C type : CK_C_GetSlotInfo
	@Field(6) 
	public Pointer<CK_C_GetSlotInfo > C_GetSlotInfo() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : CK_C_GetSlotInfo
	@Field(6) 
	public CK_FUNCTION_LIST C_GetSlotInfo(Pointer<CK_C_GetSlotInfo > C_GetSlotInfo) {
		this.io.setPointerField(this, 6, C_GetSlotInfo);
		return this;
	}
	/// C type : CK_C_GetTokenInfo
	@Field(7) 
	public Pointer<CK_C_GetTokenInfo > C_GetTokenInfo() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : CK_C_GetTokenInfo
	@Field(7) 
	public CK_FUNCTION_LIST C_GetTokenInfo(Pointer<CK_C_GetTokenInfo > C_GetTokenInfo) {
		this.io.setPointerField(this, 7, C_GetTokenInfo);
		return this;
	}
	/// C type : CK_C_GetMechanismList
	@Field(8) 
	public Pointer<CK_C_GetMechanismList > C_GetMechanismList() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : CK_C_GetMechanismList
	@Field(8) 
	public CK_FUNCTION_LIST C_GetMechanismList(Pointer<CK_C_GetMechanismList > C_GetMechanismList) {
		this.io.setPointerField(this, 8, C_GetMechanismList);
		return this;
	}
	/// C type : CK_C_GetMechanismInfo
	@Field(9) 
	public Pointer<CK_C_GetMechanismInfo > C_GetMechanismInfo() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : CK_C_GetMechanismInfo
	@Field(9) 
	public CK_FUNCTION_LIST C_GetMechanismInfo(Pointer<CK_C_GetMechanismInfo > C_GetMechanismInfo) {
		this.io.setPointerField(this, 9, C_GetMechanismInfo);
		return this;
	}
	/// C type : CK_C_InitToken
	@Field(10) 
	public Pointer<CK_C_InitToken > C_InitToken() {
		return this.io.getPointerField(this, 10);
	}
	/// C type : CK_C_InitToken
	@Field(10) 
	public CK_FUNCTION_LIST C_InitToken(Pointer<CK_C_InitToken > C_InitToken) {
		this.io.setPointerField(this, 10, C_InitToken);
		return this;
	}
	/// C type : CK_C_InitPIN
	@Field(11) 
	public Pointer<CK_C_InitPIN > C_InitPIN() {
		return this.io.getPointerField(this, 11);
	}
	/// C type : CK_C_InitPIN
	@Field(11) 
	public CK_FUNCTION_LIST C_InitPIN(Pointer<CK_C_InitPIN > C_InitPIN) {
		this.io.setPointerField(this, 11, C_InitPIN);
		return this;
	}
	/// C type : CK_C_SetPIN
	@Field(12) 
	public Pointer<CK_C_SetPIN > C_SetPIN() {
		return this.io.getPointerField(this, 12);
	}
	/// C type : CK_C_SetPIN
	@Field(12) 
	public CK_FUNCTION_LIST C_SetPIN(Pointer<CK_C_SetPIN > C_SetPIN) {
		this.io.setPointerField(this, 12, C_SetPIN);
		return this;
	}
	/// C type : CK_C_OpenSession
	@Field(13) 
	public Pointer<CK_C_OpenSession > C_OpenSession() {
		return this.io.getPointerField(this, 13);
	}
	/// C type : CK_C_OpenSession
	@Field(13) 
	public CK_FUNCTION_LIST C_OpenSession(Pointer<CK_C_OpenSession > C_OpenSession) {
		this.io.setPointerField(this, 13, C_OpenSession);
		return this;
	}
	/// C type : CK_C_CloseSession
	@Field(14) 
	public Pointer<CK_C_CloseSession > C_CloseSession() {
		return this.io.getPointerField(this, 14);
	}
	/// C type : CK_C_CloseSession
	@Field(14) 
	public CK_FUNCTION_LIST C_CloseSession(Pointer<CK_C_CloseSession > C_CloseSession) {
		this.io.setPointerField(this, 14, C_CloseSession);
		return this;
	}
	/// C type : CK_C_CloseAllSessions
	@Field(15) 
	public Pointer<CK_C_CloseAllSessions > C_CloseAllSessions() {
		return this.io.getPointerField(this, 15);
	}
	/// C type : CK_C_CloseAllSessions
	@Field(15) 
	public CK_FUNCTION_LIST C_CloseAllSessions(Pointer<CK_C_CloseAllSessions > C_CloseAllSessions) {
		this.io.setPointerField(this, 15, C_CloseAllSessions);
		return this;
	}
	/// C type : CK_C_GetSessionInfo
	@Field(16) 
	public Pointer<CK_C_GetSessionInfo > C_GetSessionInfo() {
		return this.io.getPointerField(this, 16);
	}
	/// C type : CK_C_GetSessionInfo
	@Field(16) 
	public CK_FUNCTION_LIST C_GetSessionInfo(Pointer<CK_C_GetSessionInfo > C_GetSessionInfo) {
		this.io.setPointerField(this, 16, C_GetSessionInfo);
		return this;
	}
	/// C type : CK_C_GetOperationState
	@Field(17) 
	public Pointer<CK_C_GetOperationState > C_GetOperationState() {
		return this.io.getPointerField(this, 17);
	}
	/// C type : CK_C_GetOperationState
	@Field(17) 
	public CK_FUNCTION_LIST C_GetOperationState(Pointer<CK_C_GetOperationState > C_GetOperationState) {
		this.io.setPointerField(this, 17, C_GetOperationState);
		return this;
	}
	/// C type : CK_C_SetOperationState
	@Field(18) 
	public Pointer<CK_C_SetOperationState > C_SetOperationState() {
		return this.io.getPointerField(this, 18);
	}
	/// C type : CK_C_SetOperationState
	@Field(18) 
	public CK_FUNCTION_LIST C_SetOperationState(Pointer<CK_C_SetOperationState > C_SetOperationState) {
		this.io.setPointerField(this, 18, C_SetOperationState);
		return this;
	}
	/// C type : CK_C_Login
	@Field(19) 
	public Pointer<CK_C_Login > C_Login() {
		return this.io.getPointerField(this, 19);
	}
	/// C type : CK_C_Login
	@Field(19) 
	public CK_FUNCTION_LIST C_Login(Pointer<CK_C_Login > C_Login) {
		this.io.setPointerField(this, 19, C_Login);
		return this;
	}
	/// C type : CK_C_Logout
	@Field(20) 
	public Pointer<CK_C_Logout > C_Logout() {
		return this.io.getPointerField(this, 20);
	}
	/// C type : CK_C_Logout
	@Field(20) 
	public CK_FUNCTION_LIST C_Logout(Pointer<CK_C_Logout > C_Logout) {
		this.io.setPointerField(this, 20, C_Logout);
		return this;
	}
	/// C type : CK_C_CreateObject
	@Field(21) 
	public Pointer<CK_C_CreateObject > C_CreateObject() {
		return this.io.getPointerField(this, 21);
	}
	/// C type : CK_C_CreateObject
	@Field(21) 
	public CK_FUNCTION_LIST C_CreateObject(Pointer<CK_C_CreateObject > C_CreateObject) {
		this.io.setPointerField(this, 21, C_CreateObject);
		return this;
	}
	/// C type : CK_C_CopyObject
	@Field(22) 
	public Pointer<CK_C_CopyObject > C_CopyObject() {
		return this.io.getPointerField(this, 22);
	}
	/// C type : CK_C_CopyObject
	@Field(22) 
	public CK_FUNCTION_LIST C_CopyObject(Pointer<CK_C_CopyObject > C_CopyObject) {
		this.io.setPointerField(this, 22, C_CopyObject);
		return this;
	}
	/// C type : CK_C_DestroyObject
	@Field(23) 
	public Pointer<CK_C_DestroyObject > C_DestroyObject() {
		return this.io.getPointerField(this, 23);
	}
	/// C type : CK_C_DestroyObject
	@Field(23) 
	public CK_FUNCTION_LIST C_DestroyObject(Pointer<CK_C_DestroyObject > C_DestroyObject) {
		this.io.setPointerField(this, 23, C_DestroyObject);
		return this;
	}
	/// C type : CK_C_GetObjectSize
	@Field(24) 
	public Pointer<CK_C_GetObjectSize > C_GetObjectSize() {
		return this.io.getPointerField(this, 24);
	}
	/// C type : CK_C_GetObjectSize
	@Field(24) 
	public CK_FUNCTION_LIST C_GetObjectSize(Pointer<CK_C_GetObjectSize > C_GetObjectSize) {
		this.io.setPointerField(this, 24, C_GetObjectSize);
		return this;
	}
	/// C type : CK_C_GetAttributeValue
	@Field(25) 
	public Pointer<CK_C_GetAttributeValue > C_GetAttributeValue() {
		return this.io.getPointerField(this, 25);
	}
	/// C type : CK_C_GetAttributeValue
	@Field(25) 
	public CK_FUNCTION_LIST C_GetAttributeValue(Pointer<CK_C_GetAttributeValue > C_GetAttributeValue) {
		this.io.setPointerField(this, 25, C_GetAttributeValue);
		return this;
	}
	/// C type : CK_C_SetAttributeValue
	@Field(26) 
	public Pointer<CK_C_SetAttributeValue > C_SetAttributeValue() {
		return this.io.getPointerField(this, 26);
	}
	/// C type : CK_C_SetAttributeValue
	@Field(26) 
	public CK_FUNCTION_LIST C_SetAttributeValue(Pointer<CK_C_SetAttributeValue > C_SetAttributeValue) {
		this.io.setPointerField(this, 26, C_SetAttributeValue);
		return this;
	}
	/// C type : CK_C_FindObjectsInit
	@Field(27) 
	public Pointer<CK_C_FindObjectsInit > C_FindObjectsInit() {
		return this.io.getPointerField(this, 27);
	}
	/// C type : CK_C_FindObjectsInit
	@Field(27) 
	public CK_FUNCTION_LIST C_FindObjectsInit(Pointer<CK_C_FindObjectsInit > C_FindObjectsInit) {
		this.io.setPointerField(this, 27, C_FindObjectsInit);
		return this;
	}
	/// C type : CK_C_FindObjects
	@Field(28) 
	public Pointer<CK_C_FindObjects > C_FindObjects() {
		return this.io.getPointerField(this, 28);
	}
	/// C type : CK_C_FindObjects
	@Field(28) 
	public CK_FUNCTION_LIST C_FindObjects(Pointer<CK_C_FindObjects > C_FindObjects) {
		this.io.setPointerField(this, 28, C_FindObjects);
		return this;
	}
	/// C type : CK_C_FindObjectsFinal
	@Field(29) 
	public Pointer<CK_C_FindObjectsFinal > C_FindObjectsFinal() {
		return this.io.getPointerField(this, 29);
	}
	/// C type : CK_C_FindObjectsFinal
	@Field(29) 
	public CK_FUNCTION_LIST C_FindObjectsFinal(Pointer<CK_C_FindObjectsFinal > C_FindObjectsFinal) {
		this.io.setPointerField(this, 29, C_FindObjectsFinal);
		return this;
	}
	/// C type : CK_C_EncryptInit
	@Field(30) 
	public Pointer<CK_C_EncryptInit > C_EncryptInit() {
		return this.io.getPointerField(this, 30);
	}
	/// C type : CK_C_EncryptInit
	@Field(30) 
	public CK_FUNCTION_LIST C_EncryptInit(Pointer<CK_C_EncryptInit > C_EncryptInit) {
		this.io.setPointerField(this, 30, C_EncryptInit);
		return this;
	}
	/// C type : CK_C_Encrypt
	@Field(31) 
	public Pointer<CK_C_Encrypt > C_Encrypt() {
		return this.io.getPointerField(this, 31);
	}
	/// C type : CK_C_Encrypt
	@Field(31) 
	public CK_FUNCTION_LIST C_Encrypt(Pointer<CK_C_Encrypt > C_Encrypt) {
		this.io.setPointerField(this, 31, C_Encrypt);
		return this;
	}
	/// C type : CK_C_EncryptUpdate
	@Field(32) 
	public Pointer<CK_C_EncryptUpdate > C_EncryptUpdate() {
		return this.io.getPointerField(this, 32);
	}
	/// C type : CK_C_EncryptUpdate
	@Field(32) 
	public CK_FUNCTION_LIST C_EncryptUpdate(Pointer<CK_C_EncryptUpdate > C_EncryptUpdate) {
		this.io.setPointerField(this, 32, C_EncryptUpdate);
		return this;
	}
	/// C type : CK_C_EncryptFinal
	@Field(33) 
	public Pointer<CK_C_EncryptFinal > C_EncryptFinal() {
		return this.io.getPointerField(this, 33);
	}
	/// C type : CK_C_EncryptFinal
	@Field(33) 
	public CK_FUNCTION_LIST C_EncryptFinal(Pointer<CK_C_EncryptFinal > C_EncryptFinal) {
		this.io.setPointerField(this, 33, C_EncryptFinal);
		return this;
	}
	/// C type : CK_C_DecryptInit
	@Field(34) 
	public Pointer<CK_C_DecryptInit > C_DecryptInit() {
		return this.io.getPointerField(this, 34);
	}
	/// C type : CK_C_DecryptInit
	@Field(34) 
	public CK_FUNCTION_LIST C_DecryptInit(Pointer<CK_C_DecryptInit > C_DecryptInit) {
		this.io.setPointerField(this, 34, C_DecryptInit);
		return this;
	}
	/// C type : CK_C_Decrypt
	@Field(35) 
	public Pointer<CK_C_Decrypt > C_Decrypt() {
		return this.io.getPointerField(this, 35);
	}
	/// C type : CK_C_Decrypt
	@Field(35) 
	public CK_FUNCTION_LIST C_Decrypt(Pointer<CK_C_Decrypt > C_Decrypt) {
		this.io.setPointerField(this, 35, C_Decrypt);
		return this;
	}
	/// C type : CK_C_DecryptUpdate
	@Field(36) 
	public Pointer<CK_C_DecryptUpdate > C_DecryptUpdate() {
		return this.io.getPointerField(this, 36);
	}
	/// C type : CK_C_DecryptUpdate
	@Field(36) 
	public CK_FUNCTION_LIST C_DecryptUpdate(Pointer<CK_C_DecryptUpdate > C_DecryptUpdate) {
		this.io.setPointerField(this, 36, C_DecryptUpdate);
		return this;
	}
	/// C type : CK_C_DecryptFinal
	@Field(37) 
	public Pointer<CK_C_DecryptFinal > C_DecryptFinal() {
		return this.io.getPointerField(this, 37);
	}
	/// C type : CK_C_DecryptFinal
	@Field(37) 
	public CK_FUNCTION_LIST C_DecryptFinal(Pointer<CK_C_DecryptFinal > C_DecryptFinal) {
		this.io.setPointerField(this, 37, C_DecryptFinal);
		return this;
	}
	/// C type : CK_C_DigestInit
	@Field(38) 
	public Pointer<CK_C_DigestInit > C_DigestInit() {
		return this.io.getPointerField(this, 38);
	}
	/// C type : CK_C_DigestInit
	@Field(38) 
	public CK_FUNCTION_LIST C_DigestInit(Pointer<CK_C_DigestInit > C_DigestInit) {
		this.io.setPointerField(this, 38, C_DigestInit);
		return this;
	}
	/// C type : CK_C_Digest
	@Field(39) 
	public Pointer<CK_C_Digest > C_Digest() {
		return this.io.getPointerField(this, 39);
	}
	/// C type : CK_C_Digest
	@Field(39) 
	public CK_FUNCTION_LIST C_Digest(Pointer<CK_C_Digest > C_Digest) {
		this.io.setPointerField(this, 39, C_Digest);
		return this;
	}
	/// C type : CK_C_DigestUpdate
	@Field(40) 
	public Pointer<CK_C_DigestUpdate > C_DigestUpdate() {
		return this.io.getPointerField(this, 40);
	}
	/// C type : CK_C_DigestUpdate
	@Field(40) 
	public CK_FUNCTION_LIST C_DigestUpdate(Pointer<CK_C_DigestUpdate > C_DigestUpdate) {
		this.io.setPointerField(this, 40, C_DigestUpdate);
		return this;
	}
	/// C type : CK_C_DigestKey
	@Field(41) 
	public Pointer<CK_C_DigestKey > C_DigestKey() {
		return this.io.getPointerField(this, 41);
	}
	/// C type : CK_C_DigestKey
	@Field(41) 
	public CK_FUNCTION_LIST C_DigestKey(Pointer<CK_C_DigestKey > C_DigestKey) {
		this.io.setPointerField(this, 41, C_DigestKey);
		return this;
	}
	/// C type : CK_C_DigestFinal
	@Field(42) 
	public Pointer<CK_C_DigestFinal > C_DigestFinal() {
		return this.io.getPointerField(this, 42);
	}
	/// C type : CK_C_DigestFinal
	@Field(42) 
	public CK_FUNCTION_LIST C_DigestFinal(Pointer<CK_C_DigestFinal > C_DigestFinal) {
		this.io.setPointerField(this, 42, C_DigestFinal);
		return this;
	}
	/// C type : CK_C_SignInit
	@Field(43) 
	public Pointer<CK_C_SignInit > C_SignInit() {
		return this.io.getPointerField(this, 43);
	}
	/// C type : CK_C_SignInit
	@Field(43) 
	public CK_FUNCTION_LIST C_SignInit(Pointer<CK_C_SignInit > C_SignInit) {
		this.io.setPointerField(this, 43, C_SignInit);
		return this;
	}
	/// C type : CK_C_Sign
	@Field(44) 
	public Pointer<CK_C_Sign > C_Sign() {
		return this.io.getPointerField(this, 44);
	}
	/// C type : CK_C_Sign
	@Field(44) 
	public CK_FUNCTION_LIST C_Sign(Pointer<CK_C_Sign > C_Sign) {
		this.io.setPointerField(this, 44, C_Sign);
		return this;
	}
	/// C type : CK_C_SignUpdate
	@Field(45) 
	public Pointer<CK_C_SignUpdate > C_SignUpdate() {
		return this.io.getPointerField(this, 45);
	}
	/// C type : CK_C_SignUpdate
	@Field(45) 
	public CK_FUNCTION_LIST C_SignUpdate(Pointer<CK_C_SignUpdate > C_SignUpdate) {
		this.io.setPointerField(this, 45, C_SignUpdate);
		return this;
	}
	/// C type : CK_C_SignFinal
	@Field(46) 
	public Pointer<CK_C_SignFinal > C_SignFinal() {
		return this.io.getPointerField(this, 46);
	}
	/// C type : CK_C_SignFinal
	@Field(46) 
	public CK_FUNCTION_LIST C_SignFinal(Pointer<CK_C_SignFinal > C_SignFinal) {
		this.io.setPointerField(this, 46, C_SignFinal);
		return this;
	}
	/// C type : CK_C_SignRecoverInit
	@Field(47) 
	public Pointer<CK_C_SignRecoverInit > C_SignRecoverInit() {
		return this.io.getPointerField(this, 47);
	}
	/// C type : CK_C_SignRecoverInit
	@Field(47) 
	public CK_FUNCTION_LIST C_SignRecoverInit(Pointer<CK_C_SignRecoverInit > C_SignRecoverInit) {
		this.io.setPointerField(this, 47, C_SignRecoverInit);
		return this;
	}
	/// C type : CK_C_SignRecover
	@Field(48) 
	public Pointer<CK_C_SignRecover > C_SignRecover() {
		return this.io.getPointerField(this, 48);
	}
	/// C type : CK_C_SignRecover
	@Field(48) 
	public CK_FUNCTION_LIST C_SignRecover(Pointer<CK_C_SignRecover > C_SignRecover) {
		this.io.setPointerField(this, 48, C_SignRecover);
		return this;
	}
	/// C type : CK_C_VerifyInit
	@Field(49) 
	public Pointer<CK_C_VerifyInit > C_VerifyInit() {
		return this.io.getPointerField(this, 49);
	}
	/// C type : CK_C_VerifyInit
	@Field(49) 
	public CK_FUNCTION_LIST C_VerifyInit(Pointer<CK_C_VerifyInit > C_VerifyInit) {
		this.io.setPointerField(this, 49, C_VerifyInit);
		return this;
	}
	/// C type : CK_C_Verify
	@Field(50) 
	public Pointer<CK_C_Verify > C_Verify() {
		return this.io.getPointerField(this, 50);
	}
	/// C type : CK_C_Verify
	@Field(50) 
	public CK_FUNCTION_LIST C_Verify(Pointer<CK_C_Verify > C_Verify) {
		this.io.setPointerField(this, 50, C_Verify);
		return this;
	}
	/// C type : CK_C_VerifyUpdate
	@Field(51) 
	public Pointer<CK_C_VerifyUpdate > C_VerifyUpdate() {
		return this.io.getPointerField(this, 51);
	}
	/// C type : CK_C_VerifyUpdate
	@Field(51) 
	public CK_FUNCTION_LIST C_VerifyUpdate(Pointer<CK_C_VerifyUpdate > C_VerifyUpdate) {
		this.io.setPointerField(this, 51, C_VerifyUpdate);
		return this;
	}
	/// C type : CK_C_VerifyFinal
	@Field(52) 
	public Pointer<CK_C_VerifyFinal > C_VerifyFinal() {
		return this.io.getPointerField(this, 52);
	}
	/// C type : CK_C_VerifyFinal
	@Field(52) 
	public CK_FUNCTION_LIST C_VerifyFinal(Pointer<CK_C_VerifyFinal > C_VerifyFinal) {
		this.io.setPointerField(this, 52, C_VerifyFinal);
		return this;
	}
	/// C type : CK_C_VerifyRecoverInit
	@Field(53) 
	public Pointer<CK_C_VerifyRecoverInit > C_VerifyRecoverInit() {
		return this.io.getPointerField(this, 53);
	}
	/// C type : CK_C_VerifyRecoverInit
	@Field(53) 
	public CK_FUNCTION_LIST C_VerifyRecoverInit(Pointer<CK_C_VerifyRecoverInit > C_VerifyRecoverInit) {
		this.io.setPointerField(this, 53, C_VerifyRecoverInit);
		return this;
	}
	/// C type : CK_C_VerifyRecover
	@Field(54) 
	public Pointer<CK_C_VerifyRecover > C_VerifyRecover() {
		return this.io.getPointerField(this, 54);
	}
	/// C type : CK_C_VerifyRecover
	@Field(54) 
	public CK_FUNCTION_LIST C_VerifyRecover(Pointer<CK_C_VerifyRecover > C_VerifyRecover) {
		this.io.setPointerField(this, 54, C_VerifyRecover);
		return this;
	}
	/// C type : CK_C_DigestEncryptUpdate
	@Field(55) 
	public Pointer<CK_C_DigestEncryptUpdate > C_DigestEncryptUpdate() {
		return this.io.getPointerField(this, 55);
	}
	/// C type : CK_C_DigestEncryptUpdate
	@Field(55) 
	public CK_FUNCTION_LIST C_DigestEncryptUpdate(Pointer<CK_C_DigestEncryptUpdate > C_DigestEncryptUpdate) {
		this.io.setPointerField(this, 55, C_DigestEncryptUpdate);
		return this;
	}
	/// C type : CK_C_DecryptDigestUpdate
	@Field(56) 
	public Pointer<CK_C_DecryptDigestUpdate > C_DecryptDigestUpdate() {
		return this.io.getPointerField(this, 56);
	}
	/// C type : CK_C_DecryptDigestUpdate
	@Field(56) 
	public CK_FUNCTION_LIST C_DecryptDigestUpdate(Pointer<CK_C_DecryptDigestUpdate > C_DecryptDigestUpdate) {
		this.io.setPointerField(this, 56, C_DecryptDigestUpdate);
		return this;
	}
	/// C type : CK_C_SignEncryptUpdate
	@Field(57) 
	public Pointer<CK_C_SignEncryptUpdate > C_SignEncryptUpdate() {
		return this.io.getPointerField(this, 57);
	}
	/// C type : CK_C_SignEncryptUpdate
	@Field(57) 
	public CK_FUNCTION_LIST C_SignEncryptUpdate(Pointer<CK_C_SignEncryptUpdate > C_SignEncryptUpdate) {
		this.io.setPointerField(this, 57, C_SignEncryptUpdate);
		return this;
	}
	/// C type : CK_C_DecryptVerifyUpdate
	@Field(58) 
	public Pointer<CK_C_DecryptVerifyUpdate > C_DecryptVerifyUpdate() {
		return this.io.getPointerField(this, 58);
	}
	/// C type : CK_C_DecryptVerifyUpdate
	@Field(58) 
	public CK_FUNCTION_LIST C_DecryptVerifyUpdate(Pointer<CK_C_DecryptVerifyUpdate > C_DecryptVerifyUpdate) {
		this.io.setPointerField(this, 58, C_DecryptVerifyUpdate);
		return this;
	}
	/// C type : CK_C_GenerateKey
	@Field(59) 
	public Pointer<CK_C_GenerateKey > C_GenerateKey() {
		return this.io.getPointerField(this, 59);
	}
	/// C type : CK_C_GenerateKey
	@Field(59) 
	public CK_FUNCTION_LIST C_GenerateKey(Pointer<CK_C_GenerateKey > C_GenerateKey) {
		this.io.setPointerField(this, 59, C_GenerateKey);
		return this;
	}
	/// C type : CK_C_GenerateKeyPair
	@Field(60) 
	public Pointer<CK_C_GenerateKeyPair > C_GenerateKeyPair() {
		return this.io.getPointerField(this, 60);
	}
	/// C type : CK_C_GenerateKeyPair
	@Field(60) 
	public CK_FUNCTION_LIST C_GenerateKeyPair(Pointer<CK_C_GenerateKeyPair > C_GenerateKeyPair) {
		this.io.setPointerField(this, 60, C_GenerateKeyPair);
		return this;
	}
	/// C type : CK_C_WrapKey
	@Field(61) 
	public Pointer<CK_C_WrapKey > C_WrapKey() {
		return this.io.getPointerField(this, 61);
	}
	/// C type : CK_C_WrapKey
	@Field(61) 
	public CK_FUNCTION_LIST C_WrapKey(Pointer<CK_C_WrapKey > C_WrapKey) {
		this.io.setPointerField(this, 61, C_WrapKey);
		return this;
	}
	/// C type : CK_C_UnwrapKey
	@Field(62) 
	public Pointer<CK_C_UnwrapKey > C_UnwrapKey() {
		return this.io.getPointerField(this, 62);
	}
	/// C type : CK_C_UnwrapKey
	@Field(62) 
	public CK_FUNCTION_LIST C_UnwrapKey(Pointer<CK_C_UnwrapKey > C_UnwrapKey) {
		this.io.setPointerField(this, 62, C_UnwrapKey);
		return this;
	}
	/// C type : CK_C_DeriveKey
	@Field(63) 
	public Pointer<CK_C_DeriveKey > C_DeriveKey() {
		return this.io.getPointerField(this, 63);
	}
	/// C type : CK_C_DeriveKey
	@Field(63) 
	public CK_FUNCTION_LIST C_DeriveKey(Pointer<CK_C_DeriveKey > C_DeriveKey) {
		this.io.setPointerField(this, 63, C_DeriveKey);
		return this;
	}
	/// C type : CK_C_SeedRandom
	@Field(64) 
	public Pointer<CK_C_SeedRandom > C_SeedRandom() {
		return this.io.getPointerField(this, 64);
	}
	/// C type : CK_C_SeedRandom
	@Field(64) 
	public CK_FUNCTION_LIST C_SeedRandom(Pointer<CK_C_SeedRandom > C_SeedRandom) {
		this.io.setPointerField(this, 64, C_SeedRandom);
		return this;
	}
	/// C type : CK_C_GenerateRandom
	@Field(65) 
	public Pointer<CK_C_GenerateRandom > C_GenerateRandom() {
		return this.io.getPointerField(this, 65);
	}
	/// C type : CK_C_GenerateRandom
	@Field(65) 
	public CK_FUNCTION_LIST C_GenerateRandom(Pointer<CK_C_GenerateRandom > C_GenerateRandom) {
		this.io.setPointerField(this, 65, C_GenerateRandom);
		return this;
	}
	/// C type : CK_C_GetFunctionStatus
	@Field(66) 
	public Pointer<CK_C_GetFunctionStatus > C_GetFunctionStatus() {
		return this.io.getPointerField(this, 66);
	}
	/// C type : CK_C_GetFunctionStatus
	@Field(66) 
	public CK_FUNCTION_LIST C_GetFunctionStatus(Pointer<CK_C_GetFunctionStatus > C_GetFunctionStatus) {
		this.io.setPointerField(this, 66, C_GetFunctionStatus);
		return this;
	}
	/// C type : CK_C_CancelFunction
	@Field(67) 
	public Pointer<CK_C_CancelFunction > C_CancelFunction() {
		return this.io.getPointerField(this, 67);
	}
	/// C type : CK_C_CancelFunction
	@Field(67) 
	public CK_FUNCTION_LIST C_CancelFunction(Pointer<CK_C_CancelFunction > C_CancelFunction) {
		this.io.setPointerField(this, 67, C_CancelFunction);
		return this;
	}
	/// C type : CK_C_WaitForSlotEvent
	@Field(68) 
	public Pointer<CK_C_WaitForSlotEvent > C_WaitForSlotEvent() {
		return this.io.getPointerField(this, 68);
	}
	/// C type : CK_C_WaitForSlotEvent
	@Field(68) 
	public CK_FUNCTION_LIST C_WaitForSlotEvent(Pointer<CK_C_WaitForSlotEvent > C_WaitForSlotEvent) {
		this.io.setPointerField(this, 68, C_WaitForSlotEvent);
		return this;
	}
}
