package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_KEY_DERIVATION_STRING_DATA extends StructObject {
	public CK_KEY_DERIVATION_STRING_DATA() {
		super();
	}
	public CK_KEY_DERIVATION_STRING_DATA(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_BYTE_PTR
	@Field(0) 
	public Pointer<Byte > pData() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : CK_BYTE_PTR
	@Field(0) 
	public CK_KEY_DERIVATION_STRING_DATA pData(Pointer<Byte > pData) {
		this.io.setPointerField(this, 0, pData);
		return this;
	}
	/// C type : CK_ULONG
	@Field(1) 
	public int ulLen() {
		return this.io.getIntField(this, 1);
	}
	/// C type : CK_ULONG
	@Field(1) 
	public CK_KEY_DERIVATION_STRING_DATA ulLen(int ulLen) {
		this.io.setIntField(this, 1, ulLen);
		return this;
	}
}
