package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_PBE_PARAMS extends StructObject {
	public CK_PBE_PARAMS() {
		super();
	}
	public CK_PBE_PARAMS(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_CHAR_PTR
	@Field(0) 
	public Pointer<Byte > pInitVector() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : CK_CHAR_PTR
	@Field(0) 
	public CK_PBE_PARAMS pInitVector(Pointer<Byte > pInitVector) {
		this.io.setPointerField(this, 0, pInitVector);
		return this;
	}
	/// C type : CK_CHAR_PTR
	@Field(1) 
	public Pointer<Byte > pPassword() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : CK_CHAR_PTR
	@Field(1) 
	public CK_PBE_PARAMS pPassword(Pointer<Byte > pPassword) {
		this.io.setPointerField(this, 1, pPassword);
		return this;
	}
	/// C type : CK_ULONG
	@Field(2) 
	public int ulPasswordLen() {
		return this.io.getIntField(this, 2);
	}
	/// C type : CK_ULONG
	@Field(2) 
	public CK_PBE_PARAMS ulPasswordLen(int ulPasswordLen) {
		this.io.setIntField(this, 2, ulPasswordLen);
		return this;
	}
	/// C type : CK_CHAR_PTR
	@Field(3) 
	public Pointer<Byte > pSalt() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : CK_CHAR_PTR
	@Field(3) 
	public CK_PBE_PARAMS pSalt(Pointer<Byte > pSalt) {
		this.io.setPointerField(this, 3, pSalt);
		return this;
	}
	/// C type : CK_ULONG
	@Field(4) 
	public int ulSaltLen() {
		return this.io.getIntField(this, 4);
	}
	/// C type : CK_ULONG
	@Field(4) 
	public CK_PBE_PARAMS ulSaltLen(int ulSaltLen) {
		this.io.setIntField(this, 4, ulSaltLen);
		return this;
	}
	/// C type : CK_ULONG
	@Field(5) 
	public int ulIteration() {
		return this.io.getIntField(this, 5);
	}
	/// C type : CK_ULONG
	@Field(5) 
	public CK_PBE_PARAMS ulIteration(int ulIteration) {
		this.io.setIntField(this, 5, ulIteration);
		return this;
	}
}
