package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_RC5_CBC_PARAMS extends StructObject {
	public CK_RC5_CBC_PARAMS() {
		super();
	}
	public CK_RC5_CBC_PARAMS(Pointer pointer) {
		super(pointer);
	}
	/**
	 * wordsize in bits<br>
	 * C type : CK_ULONG
	 */
	@Field(0) 
	public int ulWordsize() {
		return this.io.getIntField(this, 0);
	}
	/**
	 * wordsize in bits<br>
	 * C type : CK_ULONG
	 */
	@Field(0) 
	public CK_RC5_CBC_PARAMS ulWordsize(int ulWordsize) {
		this.io.setIntField(this, 0, ulWordsize);
		return this;
	}
	/**
	 * number of rounds<br>
	 * C type : CK_ULONG
	 */
	@Field(1) 
	public int ulRounds() {
		return this.io.getIntField(this, 1);
	}
	/**
	 * number of rounds<br>
	 * C type : CK_ULONG
	 */
	@Field(1) 
	public CK_RC5_CBC_PARAMS ulRounds(int ulRounds) {
		this.io.setIntField(this, 1, ulRounds);
		return this;
	}
	/**
	 * pointer to IV<br>
	 * C type : CK_BYTE_PTR
	 */
	@Field(2) 
	public Pointer<Byte > pIv() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * pointer to IV<br>
	 * C type : CK_BYTE_PTR
	 */
	@Field(2) 
	public CK_RC5_CBC_PARAMS pIv(Pointer<Byte > pIv) {
		this.io.setPointerField(this, 2, pIv);
		return this;
	}
	/**
	 * length of IV in bytes<br>
	 * C type : CK_ULONG
	 */
	@Field(3) 
	public int ulIvLen() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * length of IV in bytes<br>
	 * C type : CK_ULONG
	 */
	@Field(3) 
	public CK_RC5_CBC_PARAMS ulIvLen(int ulIvLen) {
		this.io.setIntField(this, 3, ulIvLen);
		return this;
	}
}
