package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_SSL3_KEY_MAT_PARAMS extends StructObject {
	public CK_SSL3_KEY_MAT_PARAMS() {
		super();
	}
	public CK_SSL3_KEY_MAT_PARAMS(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_ULONG
	@Field(0) 
	public int ulMacSizeInBits() {
		return this.io.getIntField(this, 0);
	}
	/// C type : CK_ULONG
	@Field(0) 
	public CK_SSL3_KEY_MAT_PARAMS ulMacSizeInBits(int ulMacSizeInBits) {
		this.io.setIntField(this, 0, ulMacSizeInBits);
		return this;
	}
	/// C type : CK_ULONG
	@Field(1) 
	public int ulKeySizeInBits() {
		return this.io.getIntField(this, 1);
	}
	/// C type : CK_ULONG
	@Field(1) 
	public CK_SSL3_KEY_MAT_PARAMS ulKeySizeInBits(int ulKeySizeInBits) {
		this.io.setIntField(this, 1, ulKeySizeInBits);
		return this;
	}
	/// C type : CK_ULONG
	@Field(2) 
	public int ulIVSizeInBits() {
		return this.io.getIntField(this, 2);
	}
	/// C type : CK_ULONG
	@Field(2) 
	public CK_SSL3_KEY_MAT_PARAMS ulIVSizeInBits(int ulIVSizeInBits) {
		this.io.setIntField(this, 2, ulIVSizeInBits);
		return this;
	}
	/// C type : CK_BBOOL
	@Field(3) 
	public byte bIsExport() {
		return this.io.getByteField(this, 3);
	}
	/// C type : CK_BBOOL
	@Field(3) 
	public CK_SSL3_KEY_MAT_PARAMS bIsExport(byte bIsExport) {
		this.io.setByteField(this, 3, bIsExport);
		return this;
	}
	/// C type : CK_SSL3_RANDOM_DATA
	@Field(4) 
	public CK_SSL3_RANDOM_DATA RandomInfo() {
		return this.io.getNativeObjectField(this, 4);
	}
	/// C type : CK_SSL3_KEY_MAT_OUT_PTR
	@Field(5) 
	public Pointer<CK_SSL3_KEY_MAT_OUT > pReturnedKeyMaterial() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : CK_SSL3_KEY_MAT_OUT_PTR
	@Field(5) 
	public CK_SSL3_KEY_MAT_PARAMS pReturnedKeyMaterial(Pointer<CK_SSL3_KEY_MAT_OUT > pReturnedKeyMaterial) {
		this.io.setPointerField(this, 5, pReturnedKeyMaterial);
		return this;
	}
}
