package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_SKIPJACK_RELAYX_PARAMS extends StructObject {
	public CK_SKIPJACK_RELAYX_PARAMS() {
		super();
	}
	public CK_SKIPJACK_RELAYX_PARAMS(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_ULONG
	@Field(0) 
	public int ulOldWrappedXLen() {
		return this.io.getIntField(this, 0);
	}
	/// C type : CK_ULONG
	@Field(0) 
	public CK_SKIPJACK_RELAYX_PARAMS ulOldWrappedXLen(int ulOldWrappedXLen) {
		this.io.setIntField(this, 0, ulOldWrappedXLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(1) 
	public Pointer<Byte > pOldWrappedX() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : CK_BYTE_PTR
	@Field(1) 
	public CK_SKIPJACK_RELAYX_PARAMS pOldWrappedX(Pointer<Byte > pOldWrappedX) {
		this.io.setPointerField(this, 1, pOldWrappedX);
		return this;
	}
	/// C type : CK_ULONG
	@Field(2) 
	public int ulOldPasswordLen() {
		return this.io.getIntField(this, 2);
	}
	/// C type : CK_ULONG
	@Field(2) 
	public CK_SKIPJACK_RELAYX_PARAMS ulOldPasswordLen(int ulOldPasswordLen) {
		this.io.setIntField(this, 2, ulOldPasswordLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(3) 
	public Pointer<Byte > pOldPassword() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : CK_BYTE_PTR
	@Field(3) 
	public CK_SKIPJACK_RELAYX_PARAMS pOldPassword(Pointer<Byte > pOldPassword) {
		this.io.setPointerField(this, 3, pOldPassword);
		return this;
	}
	/// C type : CK_ULONG
	@Field(4) 
	public int ulOldPublicDataLen() {
		return this.io.getIntField(this, 4);
	}
	/// C type : CK_ULONG
	@Field(4) 
	public CK_SKIPJACK_RELAYX_PARAMS ulOldPublicDataLen(int ulOldPublicDataLen) {
		this.io.setIntField(this, 4, ulOldPublicDataLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(5) 
	public Pointer<Byte > pOldPublicData() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : CK_BYTE_PTR
	@Field(5) 
	public CK_SKIPJACK_RELAYX_PARAMS pOldPublicData(Pointer<Byte > pOldPublicData) {
		this.io.setPointerField(this, 5, pOldPublicData);
		return this;
	}
	/// C type : CK_ULONG
	@Field(6) 
	public int ulOldRandomLen() {
		return this.io.getIntField(this, 6);
	}
	/// C type : CK_ULONG
	@Field(6) 
	public CK_SKIPJACK_RELAYX_PARAMS ulOldRandomLen(int ulOldRandomLen) {
		this.io.setIntField(this, 6, ulOldRandomLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(7) 
	public Pointer<Byte > pOldRandomA() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : CK_BYTE_PTR
	@Field(7) 
	public CK_SKIPJACK_RELAYX_PARAMS pOldRandomA(Pointer<Byte > pOldRandomA) {
		this.io.setPointerField(this, 7, pOldRandomA);
		return this;
	}
	/// C type : CK_ULONG
	@Field(8) 
	public int ulNewPasswordLen() {
		return this.io.getIntField(this, 8);
	}
	/// C type : CK_ULONG
	@Field(8) 
	public CK_SKIPJACK_RELAYX_PARAMS ulNewPasswordLen(int ulNewPasswordLen) {
		this.io.setIntField(this, 8, ulNewPasswordLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(9) 
	public Pointer<Byte > pNewPassword() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : CK_BYTE_PTR
	@Field(9) 
	public CK_SKIPJACK_RELAYX_PARAMS pNewPassword(Pointer<Byte > pNewPassword) {
		this.io.setPointerField(this, 9, pNewPassword);
		return this;
	}
	/// C type : CK_ULONG
	@Field(10) 
	public int ulNewPublicDataLen() {
		return this.io.getIntField(this, 10);
	}
	/// C type : CK_ULONG
	@Field(10) 
	public CK_SKIPJACK_RELAYX_PARAMS ulNewPublicDataLen(int ulNewPublicDataLen) {
		this.io.setIntField(this, 10, ulNewPublicDataLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(11) 
	public Pointer<Byte > pNewPublicData() {
		return this.io.getPointerField(this, 11);
	}
	/// C type : CK_BYTE_PTR
	@Field(11) 
	public CK_SKIPJACK_RELAYX_PARAMS pNewPublicData(Pointer<Byte > pNewPublicData) {
		this.io.setPointerField(this, 11, pNewPublicData);
		return this;
	}
	/// C type : CK_ULONG
	@Field(12) 
	public int ulNewRandomLen() {
		return this.io.getIntField(this, 12);
	}
	/// C type : CK_ULONG
	@Field(12) 
	public CK_SKIPJACK_RELAYX_PARAMS ulNewRandomLen(int ulNewRandomLen) {
		this.io.setIntField(this, 12, ulNewRandomLen);
		return this;
	}
	/// C type : CK_BYTE_PTR
	@Field(13) 
	public Pointer<Byte > pNewRandomA() {
		return this.io.getPointerField(this, 13);
	}
	/// C type : CK_BYTE_PTR
	@Field(13) 
	public CK_SKIPJACK_RELAYX_PARAMS pNewRandomA(Pointer<Byte > pNewRandomA) {
		this.io.setPointerField(this, 13, pNewRandomA);
		return this;
	}
}
