package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.rejna.pkcs11.Version;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_SSL3_MASTER_KEY_DERIVE_PARAMS extends StructObject {
	public CK_SSL3_MASTER_KEY_DERIVE_PARAMS() {
		super();
	}
	public CK_SSL3_MASTER_KEY_DERIVE_PARAMS(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_SSL3_RANDOM_DATA
	@Field(0) 
	public CK_SSL3_RANDOM_DATA RandomInfo() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : CK_VERSION_PTR
	@Field(1) 
	public Pointer<Version > pVersion() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : CK_VERSION_PTR
	@Field(1) 
	public CK_SSL3_MASTER_KEY_DERIVE_PARAMS pVersion(Pointer<Version > pVersion) {
		this.io.setPointerField(this, 1, pVersion);
		return this;
	}
}
