package xltck;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : xltCk.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("xltCk") 
public class CK_SESSION_INFO extends StructObject {
	public CK_SESSION_INFO() {
		super();
	}
	public CK_SESSION_INFO(Pointer pointer) {
		super(pointer);
	}
	/// C type : CK_SLOT_ID
	@Field(0) 
	public int slotID() {
		return this.io.getIntField(this, 0);
	}
	/// C type : CK_SLOT_ID
	@Field(0) 
	public CK_SESSION_INFO slotID(int slotID) {
		this.io.setIntField(this, 0, slotID);
		return this;
	}
	/// C type : CK_STATE
	@Field(1) 
	public int state() {
		return this.io.getIntField(this, 1);
	}
	/// C type : CK_STATE
	@Field(1) 
	public CK_SESSION_INFO state(int state) {
		this.io.setIntField(this, 1, state);
		return this;
	}
	/**
	 * see below<br>
	 * C type : CK_FLAGS
	 */
	@Field(2) 
	public int flags() {
		return this.io.getIntField(this, 2);
	}
	/**
	 * see below<br>
	 * C type : CK_FLAGS
	 */
	@Field(2) 
	public CK_SESSION_INFO flags(int flags) {
		this.io.setIntField(this, 2, flags);
		return this;
	}
	/**
	 * ulDeviceError was changed from CK_USHORT to CK_ULONG for<br>
	 * v2.0<br>
	 * device-dependent error code<br>
	 * C type : CK_ULONG
	 */
	@Field(3) 
	public int ulDeviceError() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * ulDeviceError was changed from CK_USHORT to CK_ULONG for<br>
	 * v2.0<br>
	 * device-dependent error code<br>
	 * C type : CK_ULONG
	 */
	@Field(3) 
	public CK_SESSION_INFO ulDeviceError(int ulDeviceError) {
		this.io.setIntField(this, 3, ulDeviceError);
		return this;
	}
}
